In [1]:
# Import packages.
import cvxpy as cp
import numpy as np

# Generate a random SDP.
n = 3
p = 3
np.random.seed(1)
C = np.random.randn(n, n)
A = []
b = []
for i in range(p):
    A.append(np.random.randn(n, n))
    b.append(np.random.randn())

# Define and solve the CVXPY problem.
# Create a symmetric matrix variable.
Q = cp.Variable((n,n), symmetric=True)
# The operator >> denotes matrix inequality.
constraints = [Q >> 0]
constraints += [
    cp.trace(A[i]@X) == b[i] for i in range(p)
]
prob = cp.Problem(cp.Minimize(cp.trace(Q)),
                  constraints)
prob.solve()

# Print result.
print("The optimal value is", prob.value)
print("A solution X is")
print(X.value)

The optimal value is 2.654351510231586
A solution X is
[[ 1.60805795 -0.59770492 -0.69576152]
 [-0.59770492  0.22229041  0.24689363]
 [-0.69576152  0.24689363  1.39679885]]


In [4]:
X

Variable((3, 3), symmetric=True)