In [1]:
import numpy as np
import pandas as pd
import cvxpy as cp

In [73]:
n = 5
A = np.zeros([n,n])
for j in range(5):
    A[0] = [np.random.random()*(1+int(x==0)) for x in range(5)]
    A[0] = A[0]/np.sum(A[0])

for i in range(1,5):
    A[i] =[np.random.random()*3]+[np.random.random()*(3-int((abs(i-j)+1)/2)) for j in range(1,5)]
    A[i] = A[i]/np.sum(A[i])
    
A

AttributeError: module 'numpy' has no attribute 'seed'

In [4]:
O = np.array([42,17,13,20,8])
x0 = np.array([30,20,20,15,15])
B = np.zeros([n**2,n])
for i in range(n**2):
    for j in range(n):
        a = int(i/n)
        b = (i)%n
        if j == a:
            if b != a:
                B[i][j] = -1
        if j == b:
            if b != a:
                B[i][j] = 1

In [7]:
def get_x_t(t):
    s = 0
    xt = x0
    while t>s:
        xt = np.dot(xt,A)
        s+=1
    return xt

In [65]:
T = 3
x = [get_x_t(t) for t in range(T)]

In [66]:
def get_x_t_B(t,ut):
    s = 0
    xt = x0
    while t>s:
        xt = np.dot(xt,A)+np.dot(ut,B)
        s+=1
    return xt

In [67]:
u = cp.Variable(n**2*T, integer=True)
x = cp.Variable()
S= np.identity(n)
x1 = [get_x_t_B(t,u[n**2*t:n**2*t+n**2]) for t in range(T)]
objective = cp.Minimize(
    np.sum([cp.sum_squares(O-np.round(A@x[i])-u[n**2*i:n**2*i+n**2]@B) for i in range(T-1)])
    +cp.quad_form(x[T-1], S)
)
constraints = [
               np.ones(n**2*T)@u <= 100,
                u >= 0
               ]

prob = cp.Problem(objective,
                 constraints)
prob.solve()

2187.265019248613

In [71]:
x

[array([30, 20, 20, 15, 15]),
 array([31.54670732, 12.25636134, 14.58652145, 19.96808917, 21.64232072]),
 array([28.49767713, 13.32871785, 16.16623952, 17.14129877, 24.86606672])]

In [72]:
x1

[array([30, 20, 20, 15, 15]), array([[Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,))],
        [Expression(AFFINE, UNKNOWN, (25,)),
         Expression(AFFINE, UNKNOWN, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,))],
        [Expression(AFFINE, UNKNOWN, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, UNKNOWN, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,))],
        [Expression(AFFINE, UNKNOWN, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,)),
         Expression(AFFINE, UNKNOWN, (25,)),
         Expression(AFFINE, NONNEGATIVE, (25,))],
        [Ex

In [37]:
u.value

array([2.60906511e-10, 3.47785525e-10, 3.45917448e-10, 8.93414395e-10,
       4.51347862e-10, 9.99999990e-01, 2.60906511e-10, 2.00636776e-09,
       2.56880310e-09, 2.11483857e-09, 2.99999999e+00, 2.01035216e-09,
       2.60906511e-10, 2.57067021e-09, 2.11682468e-09, 3.13852823e-09,
       1.45196756e-09, 1.44995149e-09, 2.60906511e-10, 1.55749517e-09,
       6.99999999e+00, 1.90209827e-09, 1.90010393e-09, 2.46144908e-09,
       2.60906511e-10, 2.60906511e-10, 2.80853853e-10, 2.80911515e-10,
       8.51108145e-10, 2.81654387e-10, 2.99999999e+00, 2.60906511e-10,
       2.00836908e-09, 2.59429018e-09, 2.00931582e-09, 1.99999999e+00,
       2.00835406e-09, 2.60906511e-10, 2.59430503e-09, 2.00930373e-09,
       3.18398784e-09, 1.42723035e-09, 1.42725649e-09, 2.60906511e-10,
       1.42813518e-09, 5.99999999e+00, 2.00740059e-09, 2.00740360e-09,
       2.59327605e-09, 2.60906511e-10, 2.60906511e-10, 3.45493176e-10,
       3.44850844e-10, 6.97263162e-10, 2.26943485e-10, 9.99999990e-01,
      