In [8]:
import numpy as np
import pandas as pd
import cvxpy as cp

In [30]:
n = 5
A = np.zeros([n,n])
for j in range(5):
    A[0] = [np.random.random()*(1+int(x==0)) for x in range(5)]
    A[0] = A[0]/np.sum(A[0])

for i in range(1,5):
    A[i] =[np.random.random()*3]+[np.random.random()*(3-int((abs(i-j)+1)/2)) for j in range(1,5)]
    A[i] = A[i]/np.sum(A[i])
    

A = np.round(A,2)
A

array([[0.25, 0.21, 0.21, 0.17, 0.16],
       [0.43, 0.26, 0.15, 0.09, 0.06],
       [0.45, 0.12, 0.08, 0.23, 0.11],
       [0.13, 0.24, 0.2 , 0.27, 0.15],
       [0.1 , 0.13, 0.03, 0.39, 0.35]])

In [102]:
A1 = np.array([[0.5,0.5],[0.5,0.5]])
A1

array([[0.5, 0.5],
       [0.5, 0.5]])

In [ ]:
#x_1 = A@x_0 + B@u
#B=identity/m

In [112]:
optimal_distribution = np.array([42,17,13,20,8])
# od = np.array([0.5,0.5])

In [125]:
#say there are m number of scooters
x0 = np.array([30,20,20,15,15])
# x01 = np.array([0.4,0.6])
m = 100
n=5
# n1=2

y = optimal_distribution-np.dot(A,x0)
# y1= od-np.dot(A1,x01)
#parameters (inputs)
u = cp.Variable(n**2)
# u1 = cp.Variable(n1**2, integer=True)
#introduced slack variable
s = cp.Variable(n)
#1 transpose
c = np.ones(n)
#X matrix as defined in assignment instructions = B
X = np.zeros([n**2,n])
for i in range(n**2):
    for j in range(n):
        a = int(i/n)
        b = (i)%n
        if j == a:
            if b != a:
                X[i][j] = -1
        if j == b:
            if b != a:
                X[i][j] = 1
#Y vector as defined in assignment instructions
Y = y.reshape(-1)

In [128]:
#solving the LP for l-1 norm
#including the two separated constraints of the slack variable
constraints1 = [-u@X-s <= -Y,
                u@X-s <= Y,
               np.ones(n**2)@u <= 100,
                u >= 0
               ]

prob = cp.Problem(cp.Minimize(c.T@s+2*np.ones(n**2)@u),
                 constraints1)
prob.solve()

print("\nThe optimal value is", prob.value)
print("A solution u is")
print(np.round(u.value,1))
# sol= np.round(u.value,5)


The optimal value is 47.393742942368995
A solution u is
[-0.  -0.  -0.  -0.  -0.   2.1 -0.  -0.   0.1 -0.   3.5 -0.  -0.   0.1
 -0.  -0.  -0.  -0.  -0.  -0.   3.3 -0.  -0.   0.1 -0. ]


In [115]:
optimal_distribution

array([42, 17, 13, 20,  8])

In [116]:
np.round(np.dot(u.value,X),4)

array([21., -5., -8.,  1., -9.])

In [119]:
np.dot(A,x0)

array([20.85, 23.35, 22.6 , 19.  , 17.3 ])

In [117]:
y-np.dot(u.value,X)

array([ 0.15, -1.35, -1.6 ,  0.  , -0.3 ])

In [85]:
X

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])